
version: "3.2"

services:
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    #      KEYCLOAK_IMPORT: ./realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - "8080:8080"
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
  users:
    ports:
      - "8000:8000"
    image: "025504720348.dkr.ecr.sa-east-1.amazonaws.com/construcao-users:latest"
    depends_on:
      - keycloak